### ISSUE TITLE
Ao clonar no Android Studio Apresenta erros

### ISSUE THREAD

**Issue by moraistv** [dvd-castro/MeuRastreio#1]
Gradle sync failed: Could not get unknown property 'props' for SigningConfig_Decorated{name=relase, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=pkcs12, v1SigningEnabled=true, v2SigningEnabled=true, enableV1Signing=null, enableV2Signing=null, enableV3Signing=null, enableV4Signing=null} of type com.android.build.gradle.internal.dsl.SigningConfig. (2 s 402 ms)

![278445731_2112972542196671_3292749813125453175_n](https://user-images.githubusercontent.com/48336092/162850708-81d8d8dc-1173-43c1-82f0-df519d6ef065.jpg)

**Comment by dvd-castro** [comment]
Opa Sebastian, tudo bem? esse erro acontece porque as opções de assinatura  em release estão ausentes, mudando para de release para debug, em **build variants**, deve resolver o problema
